### ISSUE TITLE
1차 ERD 에 대한 의견입니다. COMMENT 부탁드립니다. 

### ISSUE THREAD

**Issue by jjoung-2j** [SsangyongProject/JobMarket_TeamProject#1]
# 개요
1차 ERD 에 대한 의견입니다. COMMENT 부탁드립니다. 아직 부족한 점이 많으니 다들 도와주세요. 

- 현재 1차 ERD
![JobMarket_1차 ERD](https://github.com/SsangyongProject/JobMarket_TeamProject/assets/145014345/c6bcd14a-afee-47ba-9896-f3fe6cec5806)

## **요구사항**
구직자 TBL
- 취업우대 / 병역  컬럼을 나눔
=> 취업우대 컬럼과 병역유무 컬럼

지역 TBL
- 지역코드를 지역일련번호로 이름변경
=> 연결되어 있는 이력서와 기업 TBL 도 이름 변경됨.

기업 TBL
- 사업자등록번호 Unique 설정
=> 구직자 tbl 에 주민번호 처럼 기업도 해야하지 않을까 하는 의견

채용공고 TBL
- 채용공고번호를 채용공고일련번호로 이름변경
=> 연결되어 있는 채용공고상세도 이름 변경됨. 
+ 의견. 채용공고일련번호나 채용공고번호가 동일할 것으로 생각이 되어 이때 연결을 초록색(실선)에 EXACTLY-ONE 으로 연결하면 어떨까 하는 의견

채용공고 상세 TBL
- 근무지역, 필수사항, 우대사항 컬럼 추가

## 요구사항을 반영한 모습
<img width="523" alt="JobMarket_1차 ERD의견" src="https://github.com/SsangyongProject/JobMarket_TeamProject/assets/145014345/d2c04d05-b105-46fa-812c-e11acfc6bdd5">

**Comment by jjoung-2j** [comment]
## 추가사항
지역 TBL - 지역일련번호 / 지역명 / 도시명 => 컬럼으로 구분
업종 TBL - 업종일련번호 / 대분류 / 중분류 / 소분류 => 컬럼으로 구분

**Comment by sonhj0125** [comment]
확인했습니다! 혹시 구직자 tbl에 취업우대는 어떤걸까요?

**Comment by kudi03628** [comment]
확인했습니다! 일단 저도 지역명테이블 지역일련번호. 도시명 컬럼으로 축소해서 컬럼값으로 나타내는게 나은거같습니다

**Comment by yerin9195** [comment]
확인했습니다. 취업우대는 보훈여부 등이 들어가면 될 거 같습니다!

**Comment by sonhj0125** [comment]
> 확인했습니다. 취업우대는 보훈여부 등이 들어가면 될 거 같습니다!

그럼 국가유공자, 장애여부, 인턴경험여부 이런게 들어가면 되겠네욯

**Comment by test-Nel** [comment]
확인했습니다.
취업우대의 경우 잡코리아를 벤치마킹해 온 것이라 유첨드린 파일 참고주시면 좋을 것 같습니다.
![스크린샷 2024-03-07 090211](https://github.com/SsangyongProject/JobMarket_TeamProject/assets/156769298/ba5d5850-2d4b-443a-ae74-217098403a45)
![스크린샷 2024-03-07 122900](https://github.com/SsangyongProject/JobMarket_TeamProject/assets/156769298/5fe51754-106f-4597-b94c-5e82c1238f78)
![스크린샷 2024-03-07 122921](https://github.com/SsangyongProject/JobMarket_TeamProject/assets/156769298/41506a34-02f1-4edd-8f2e-415ec73f5889)

**Comment by jjoung-2j** [comment]
취업우대코드로 그럼 병합한 다음에 그 속에 병역, 국가유공자 등 넣으면 될것같아요
